[project]
name = "electronic-instrumentation"
version = "1.0.0"
description = "EI manuals"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "download-link-replacer>=1.0.6",
    "jupyterbook-patches>=1.13.4",
    "sphinx-accessibility>=1.0.1",
    "sphinx-exercise>=1.2.1",
    "sphinx-iframes>=1.2.0",
    "sphinx-image-inverter>=1.1.11",
    "sphinx-thebe",
    "teachbooks>=0.2.4",
    "teachbooks-sphinx-tippy>=1.0.15",
    "sphinx-dropdown-toggle>=1.3",
    "jupyter-book-duplicate-toc-entry",
    "watchdog[watchmedo]>=6.0.0",
    "numpy>=2.5.0",
    "matplotlib>=3.11.0",
    "plotly>=6.9.0",
]

[tool.uv.sources]
sphinx-thebe = { git = "https://github.com/TeachBooks/Sphinx-Thebe" }
jupyter-book-duplicate-toc-entry = { git = "https://github.com/NB-TUDelft/jupyter-book-duplicate-toc-entry.git" }
