name: call-deploy-book

on:
  push:
    branches:
    - main
    paths:
    - book/**
    - requirements.txt
    - .github/workflows/call-deploy-book.yml
  workflow_dispatch:

jobs:
  # First create the EI manuals archive
  create-archive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create EI manuals archive
      run: |
        zip -r -Z bzip2 -9 ./book/static/EI_manuals.zip ./book/EI_manuals/
        
        echo "Archive created successfully!"
        ls -lh ./book/static/
    
    - name: Commit archive if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add book/static/EI_manuals.zip
        git diff --staged --quiet || {
          git commit -m "Update EI manuals archive [skip actions]"
          git push
        }
  
  # Then deploy the book
  deploy-book:
    needs: create-archive  # Wait for archive to be created
    uses: TeachBooks/deploy-book-workflow/.github/workflows/deploy-book.yml@main
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write